apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - statefulset.yaml
  - service.yaml
  - service-headless.yaml

namespace: prometheus

commonLabels:
  app: prometheus