apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress/base/nginx
  - monitor
  - alert-manager-webhook
  - database

patchesStrategicMerge:
  - patches/nginx/default-cert-patch.yaml
